spring:
  application:
    name: day95

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##user1
    password: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082
  