spring:
  application:
    name: day96

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##user1
    password: 1

server:
  port: 8083