spring:
  application:
    name: day94
    
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##user2
    password: 2
    
server:
  port: 8081
